return {
	-- "zbirenbaum/copilot.lua",
	-- dependencies = {
	-- 	"copilotlsp-nvim/copilot-lsp",
	-- },
	-- -- event = { "VeryLazy" },
	-- -- lazy = true,
	-- config = function()
	-- 	local copilot = require("copilot")
	-- 	copilot.setup({
	-- 		panel = {
	-- 			enabled = true,
	-- 			auto_refresh = false,
	-- 			keymap = {
	-- 				jump_prev = "[[",
	-- 				jump_next = "]]",
	-- 				accept = "<CR>",
	-- 				refresh = "gr",
	-- 				open = "<M-CR>",
	-- 			},
	-- 			layout = {
	-- 				position = "bottom", -- | top | left | right | bottom |
	-- 				ratio = 0.4,
	-- 			},
	-- 		},
	-- 		suggestion = {
	-- 			enabled = true,
	-- 			auto_trigger = true,
	-- 			hide_during_completion = true,
	-- 			debounce = 75,
	-- 			trigger_on_accept = true,
	-- 			keymap = {
	-- 				accept = "<M-l>",
	-- 				accept_word = false,
	-- 				accept_line = false,
	-- 				next = "<M-]>",
	-- 				prev = "<M-[>",
	-- 				dismiss = "<C-]>",
	-- 			},
	-- 		},
	-- 		nes = {
	-- 			enabled = false, -- requires copilot-lsp as a dependency
	-- 			auto_trigger = false,
	-- 			keymap = {
	-- 				accept_and_goto = false,
	-- 				accept = false,
	-- 				dismiss = false,
	-- 			},
	-- 		},
	-- 		copilot_node_command = "node", -- Node.js version must be > 22
	-- 		workspace_folders = {},
	-- 		copilot_model = "",
	-- 		disable_limit_reached_message = false, -- Set to `true` to suppress completion limit reached popup
	-- 		server_opts_overrides = {},
	-- 	})
	-- end,
}
